server:
  port: 8081  # Puerto específico para auth-service

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb  # Cambia a MySQL si es necesario
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

security:
    jwt:
        secret: mySuperSecretKey
        expiration: 3600000  # 1 hora en milisegundos

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
